apiVersion: v1
kind: Service
metadata:
  name: deepseekv4flash
  labels:
    app.kubernetes.io/name: deepseekv4flash
    app.kubernetes.io/part-of: deepseekv4flash
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: deepseekv4flash
    app.kubernetes.io/part-of: deepseekv4flash
  ports:
    - name: http
      port: 80
      targetPort: 3000
