apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deepseekv4flash
  namespace: argocd
spec:
  project: deepseekv4flash
  source:
    repoURL: https://github.com/gateszhangc/deepseekv4flash.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: deepseekv4flash
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
