apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deepseekv4flash
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/deepseekv4flash
    newName: registry.144.91.77.245.sslip.io/deepseekv4flash
    newTag: 86ba2761d95eb8f76a3e06232bf13d6947e29b40
