apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deepseekv4flash
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/deepseekv4flash
    newName: registry.144.91.77.245.sslip.io/deepseekv4flash
    newTag: 8e56d0f8cd4552aab1b11cd64961e1d08609f3ff
